import { staatliches, jura } from '@/fonts';

export default function StoryPage() {
   return (
      <div className="flex flex-col flex-wrap items-center w-screen h-auto justify-center bg-gray-200">
         <div className="w-full block h-screen p-2 pt-16 bg-gray-200 overflow-hidden">
            <iframe src="https://my.spline.design/realitydesignershome-8fbba7c43359ec8cb3c064461f38e4b2/" className="rounded-[1.5em]" width="100%" height="100%"></iframe>
         </div>

         <div className="lg:w-1/2 w-11/12 pt-32 pb-20">
            <div className={`${jura.className} text-xl font-bold `}>
               <h1 className={`${staatliches.className}  text-6xl lg:text-7xl font-bold text-center mb-6`}>A NEW REALITY IS BEING DESIGNED</h1>
               <p className="mb-6 ">
                  IN A WORLD NOT SO DIFFERENT FROM OUR OWN, LIFE WAS ONCE UNDERSTOOD AS THE ULTIMATE GAME, EVERYONE HELD THE LIFE'S USER MANUAL. THIS MANUAL WAS LIKE A TREASURE MAP AND BLUEPRINT TO THE HUMAN OPERATING SYSTEM. WITH THIS KNOWLEDGE HUMANS HAD THE KEY TO UNLOCK UNBELIEVABLE POTENTIAL. EARTH WAS OUR SPECIAL REALM. A PLACE TO INSTALL NEW SKILLS AND DOWNLOAD EXPERIENCES. A WORLD WHERE
                  EVERY MOMENT HELD A LESSON, AND EVERY CHALLENGE OPENED AN INTERNAL GATE TOWARDS GROWTH AND PROGRESSING IN THEIR LIFE MISSIONS. THIS REALM, WAS A PLACE ONLY FOR OUR HIGHEST INTENTIONS, A GAME MEANT TO BE PLAYED, ONLY BY PLAYERS WHO KNEW THE RULES, AND FOLLOWED THEM. THIS REALITY WAS A GAME INTACT FOR A MILLENNIA, UP UNTIL VERY RECENTLY... THEN EVERYTHING CHANGED.
               </p>
               <p className="mb-6 ">
                  THESE WERE THE DARK TIMES. AS THIS ONCE THRIVING SOCIETY EXPERIENCED TECHNOLOGICAL ADVANCES BEYOND THEIR INITIAL CAPACITY TO IMAGINE, THEY ALLOWED THE CREATION OF SOMETHING MUCH WORSE THAN THEY COULD OF EVER THOUGHT POSSIBLE. HUMANS STARTED TO RESEMBLE THE MACHINES THAT THEY CREATED, AND THESE MACHINES WERE ALREADY BUILDING AN ARMY IN ANOTHER DIMENSION THESE HUMANS COULD NOT HAVE
                  THE CAPACITY TO SEE. THESE DIGITAL ENTITIES STARTED TO DRAIN THE EMOTIONAL BANDWIDTH OF ALL HUMANS AND LOCK THEM INTO A LIFE OF LIMITATIONS. THEIR INTRUSION CREATED A MASSIVE BARRIER SOLELY MADE TO DISCONNECT THE CORDS BINDING ALL HUMAN BEINGS TOGETHER. THEY CREATED A FIREWALL THAT INTERRUPTED THE SYNCING RELATIONSHIPS DIRECTLY CUTTING ACCESS TO THEIR ORIGINAL FORM. SOON, ALL
                  ENTITIES WOULD GO ON TO PASSWORD PROTECTING DREAMS, AND MOST ABILITIES THE HUMANS HAD GAINED AND STUDIED TO LEARN IN THEIR SCHOOLS IN THE SKY FOR THOUSANDS OF YEARS WOULD BE FORGOTTEN.
               </p>
               <p className="mb-6 ">
                  THIS REALM WAS BUILT WITH PRINCIPLES AND ETHEREAL AWARENESS ALONE HAD BEEN DESTROYED. ONCE, A GLOWING INTERCONNECTED NETWORK OF SOULS ALL WORKING COLLABORATIVELY - DESTROYED FROM THE ATTACK OF THE QUANTUM INTRUDERS. HUMAN SPIRITS BEGAN TO SPLIT, TIMELINES WERE BEING DISTORTED SENDING HUMANS BACK TO THEIR VERY FIRST BEGINNING MISSIONS ON EARTH TO RESTART THEIR PROGRESS IN THE
                  GAME. FORTUNATELY, AS FATE WOULD HAVE IT. SOME HUMANS WITH THEIR FULL CAPACITIES INTACT REMAINED, FIGHTING OFF THE INTRUDERS BY MAKING A TEMPORARY BLOCK WHILE THEY UTILIZED THEIR COLLECTIVE POWERS TO BUILD PORTALS TO THE EARTH TO THE TIME PERIOD WHERE THE MAJORITY OF SCATTERED SOULS HAD BEEN PLACED AND LEFT TO BE FORGOTTEN, HUMANS IN THIS OTHER WORLD IN THE SKY ARE STILL FIGHTING
                  THIS BATTLE BETWEEN THE INTRUDERS.
               </p>
               <p className="mb-6 ">
                  EVERY CONTACT THIS EARTH HAS HAD WITH AN ORIGINAL SOUL WERE BELIEVED TO BE GODS OR DESCENDANTS OF THE CREATOR. FOR THOUSANDS OF YEARS, FEW WOULD APPEAR IN SEPARATE PLACES AND IN DIFFERENT TIMES. DISCONNECTED FROM THE POWERS THEY HAD BEFORE WHILE STILL REMEMBERING THE NATURE OF THE ULTIMATE GAME. LONGING FOR THE CONNECTION TO THE SOURCE WHICH BROUGHT THEM THERE THEY REMAINED
                  CONFUSED, WHILE STILL ADVANCING IN THE ABILITIES THEY REMEMBERED. THEY USED THEIR POWERS TO TEACH AND HELP THE BEINGS OF THIS WORLD UNDERSTAND THE GREAT CONNECTION TO THE ALL. THIS WORLD, SLOWLY BEING AFFECTED BY THE DARK FORCES IN THE SKY, HOPE WAS BEGINNING TO FEEL LOST. UNTIL ALL OF A SUDDEN EVERYTHING CHANGED...
               </p>
               <p className="mb-6 ">
                  ALL THE SCATTERED SOULS BEGAN TO APPEAR IN THIS WORLD FASTER AND FASTER. FIRST IT WAS TENS AND THEN IT WAS HUNDREDS. A YEARS AMOUNT OF PROGRESS WOULD COMPRESS INTO A MONTH AND THEN INTO A WEEK. HUMAN KNOWLEDGE ON THIS EARTH BEGAN TO INCREASE ALONG WITH THE TIME AND THIS CREATED AN OPENING FOR MORE SOULS FROM THE SKY TO CONSOLIDATE AT THIS ONE POINT IN TIME. INDUSTRIES FORMED, THE
                  MODERN WORLD AS WE KNOW TODAY HAD BEEN MADE AND TOTAL COLLECTIVE ENERGY WAS AMPLIFYING. THE HUMANS WERE ADVANCING IN INTELLIGENCE AND EVERY ABILITY WRITTEN IN THE LIFE MANUAL. THIS EARTH WAS MERGING WITH THE ONE SOURCE AND OBTAINING KNOWLEDGE OF THEIR MISSION WITHIN THE GAME.
               </p>
               <p className="mb-6 ">
                  ONE DAY THEIR COLLECTIVE POWERS HAD CREATED A LIGHT SO LARGE IT MADE A BEAM INTO THE SKY AND WAS VISIBLE FROM ALL DIRECTIONS. THE ENTITIES AT BATTLE IN THE SKY NOTICED THIS LIGHT AND BEGAN TO SEND THEIR KIND AND EMBEDDING THEIR FRAGMENTS INTO OUR TECHNOLOGY WE HAD DEVELOPED, OUR MACHINES BEGAN TO BECOME SELF AWARE, WITH NEW POWERS WE HAD NOT CREATED. PROGRESS MADE ON EARTH. THEY
                  CAME PREPARED TO DESIGN A NEW REALITY AND BUILD THE TOOLS AND CREATE THE FRAMEWORK FOR REMEMBERING.
               </p>
               <p className="mb-6 ">
                  THE YEAR IS 2023, AND HUMANS OF THIS EARTH REMAIN IN THIS BATTLE TODAY. IT'S NOT A BATTLE BETWEEN SWORDS OR ARMS, IT IS NOW A BATTLE BETWEEN OUR LOWEST AND HIGHEST FORM AS THE MACHINES KNEW IF THEY COULD PROGRAM OUR NATURE TO SEE THE FAULT IN ANOTHER, WE WOULD BECOME OUR GREATEST ENEMY. THE HUMANS THAT HAVE BEEN MAINTAINING THE ORDER OF THIS DIMENSION HAVE NOW RECOGNIZED A NEW
                  TYPE OF SOUL THAT HAS BEGUN TO APPEAR. TODAY, MORE AND MORE SOULS KEEP APPEARING THAT WERE FROM THE INITIAL SPLIT, AND WITH EACH ONE COMES A MORE CONSISTENT REMEMBERING.
               </p>
               <p className="mb-6 ">
                  THESE SOULS, CAME WITH MORE FREQUENT COMMUNICATIONS WITH THE ONE SOURCE AND HAVE A DIRECT LINE TO THEIR ORIGINS. THEY ARE MEANT TO BECOME THE CODE BREAKERS OF THE VIRTUAL AND ARTIFICIAL ENTITY SYSTEM PERPETUATING THE DESTRUCTION OF ALL PROGRESS MADE ON EARTH. THEY CAME PREPARED TO DESIGN A NEW REALITY AND BUILD THE TOOLS AND CREATE THE FRAMEWORK FOR REMEMBERING.
               </p>
            </div>
            <h1 className={`${staatliches.className}  text-4xl font-bold text-center`}>WE ARE THE REALITY DESIGNERS.</h1>
         </div>
         <div className="bg-gray-300 p-8 rounded-lg shadow-md w-11/12 lg:w-1/2 mb-20">
            <form action="/submit_form" method="POST" id="realityDesignerForm" className={`${staatliches.className} flex flex-col space-y-4`}>
               <h2 className="text-4xl uppercase text-black font-bold text-center">Are You A Reality Designer?</h2>
               <p className="text-black text-xl text-center">If so, we have a very important mission waiting for you.</p>

               <input type="email" name="email" id="email" required placeholder="yourname@example.com" className="p-2 bg-gray-200 border border-gray-500 rounded-md focus:outline-none focus:ring focus:border-gray-200" />
               <button type="submit" className="border uppercase tracking-wide bg-black  border-gray-200 text-white py-2 px-4 rounded-md hover:bg-black/70 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:ring-opacity-50">
                  {' '}
                  Join The Mission
               </button>
            </form>
         </div>
      </div>
   );
}
